In [1]:
# Librerias a usar
import numpy as np

In [2]:
# Transforma el sistema Ax = b al sistema x = Ty + c
def transformar_sistema(A, b):
    # Inicializar la matriz de transformación T
    T = np.zeros_like(A, dtype=float)

    # Iterar sobre las filas de la matriz A
    for i in range(len(A)):
        # Seleccionar la fila actual y los elementos de la diagonal
        fila_actual = A[i]
        diag_element = fila_actual[i]

        # Despejar xi de la ecuación correspondiente
        for j in range(len(fila_actual)):
            if j != i:
                T[i][j] = -fila_actual[j] / diag_element

        T[i][i] = 0

    c = b / np.diag(A)
    return T, c

In [5]:
def metodo_gauss(T, c, v_0, tol, n_iteration, norm):
    
    norm_xk = 0
    norm_xk_v0 = 0
    error = np.array([0])
    table_xk = np.array([v_0])

    for n in range(n_iteration):

        xk = np.zeros_like(c, dtype=float)
        # Calculo del vector x_k
        for i in range(len(T)):

            if i == 0:
                xk[i] = np.round(np.dot(T[i, :], v_0) + c[i], 4)
            elif i == len(T) - 1:
                xk[i] = np.round(np.dot(T[i, :], xk), 4) + np.round(c[i], 4)
            else:
                xk[i] = np.round(np.round(np.dot(T[i, :i], xk[:i]), 4) + np.round(np.dot(T[i, i + 1:], v_0[i + 1:]),
                                                                                  4) + np.round(c[i], 4), 4)

        if norm == 1:
            norm_xk_v0 = np.linalg.norm(xk - v_0, np.inf)
            norm_xk = np.linalg.norm(xk, np.inf)
        if norm == 2:
            norm_xk_v0 = np.linalg.norm(xk - v_0)
            norm_xk = np.linalg.norm(xk)

        error = np.append(error, norm_xk_v0 / norm_xk)

        table_xk = np.append(table_xk, [xk])

        v_0 = xk

        if error[n + 1] < tol:
            return table_xk.reshape(n + 2, len(T)).transpose(), error

    return table_xk.reshape(n_iteration + 1, len(T)).transpose(), error


In [3]:
# Definición del sistema lineal a resolver y el vector inicial v_0

Ax_b = np.array([[10, -1, 2, 0, 6],
                 [-1, 11, -1, 3, 25],
                 [2, -1, 10, -1, -11],
                 [0, 3, -1, 8, 15]])
v_0 = np.array([0, 0, 0, 0])
print(f'El sistema Ax = b:\n{Ax_b[:, :-1]} = \n{Ax_b[:, -1].reshape((4, 1))}\n\nEl vector inicial es:\n{v_0}')

El sistema Ax = b:
[[10 -1  2  0]
 [-1 11 -1  3]
 [ 2 -1 10 -1]
 [ 0  3 -1  8]] = 
[[  6]
 [ 25]
 [-11]
 [ 15]]

El vector inicial es:
[0 0 0 0]


In [4]:
# Sacamos su transformación x = Ty + c
T, c = transformar_sistema(Ax_b[:, :-1], Ax_b[:, -1])
print(f'La transformación x=Ty+c es definida por T:\n{T}\nEl vector c:\n{c}')

La transformación x=Ty+c es definida por T:
[[ 0.          0.1        -0.2         0.        ]
 [ 0.09090909  0.          0.09090909 -0.27272727]
 [-0.2         0.1         0.          0.1       ]
 [ 0.         -0.375       0.125       0.        ]]
El vector c:
[ 0.6         2.27272727 -1.1         1.875     ]


In [6]:
table_xk, error = metodo_gauss(T, c, v_0, tol=10 ** (-3), n_iteration=10, norm=1)
table_xk

array([[ 0.    ,  0.6   ,  1.0302,  1.0066,  1.0009,  1.0001],
       [ 0.    ,  2.3272,  2.0369,  2.0035,  2.0003,  2.    ],
       [ 0.    , -0.9873, -1.0144, -1.0026, -1.0003, -1.    ],
       [ 0.    ,  0.8789,  0.9844,  0.9984,  0.9998,  1.    ]])

In [7]:
error

array([0.00000000e+00, 1.00000000e+00, 2.11203299e-01, 1.66708261e-02,
       2.84957256e-03, 4.00000000e-04])