In [1]:
import numpy as np

In [2]:
# Transforma el sistema Ax = b al sistema Tx = c
def transformar_sistema(A, b):
    # Inicializar la matriz de transformación T
    T = np.zeros_like(A, dtype=float)

    # Iterar sobre las filas de la matriz A
    for i in range(len(A)):
        # Seleccionar la fila actual y los elementos de la diagonal
        fila_actual = A[i]
        diag_element = fila_actual[i]

        # Despejar xi de la ecuación correspondiente
        for j in range(len(fila_actual)):
            if j != i:
                T[i][j] = -fila_actual[j] / diag_element

        T[i][i] = 0

    c = b / np.diag(A)
    return T, c

In [3]:
# Definición de la función para el método Jacobi

def met_jacobi(T, c, v_0, tol, n_iteration, norm):
    norm_vk = 0
    norm_v0_vk = 0
    error = 0
    table_vk = np.array([v_0])
    for i in range(0, n_iteration):
        # Matriz por vector para hallar el vector k-ésimo

        v_k = np.round(np.dot(T, v_0) + c, 4)

        # Calculo de la norma
        if norm == 1:
            norm_v0_vk = np.linalg.norm(v_k - v_0, np.inf)
            norm_vk = np.linalg.norm(v_k, np.inf)
        elif norm == 2:
            norm_v0_vk = np.linalg.norm(v_k - v_0)
            norm_vk = np.linalg.norm(v_k)

        # Calculo del error relativo
        error = norm_v0_vk / norm_vk
        v_0 = v_k
        table_vk = np.append(table_vk, [v_k])
        if error <= tol:
            return table_vk.reshape(i + 2, len(T)).transpose(), error

    return table_vk.reshape(n_iteration + 1, len(T)).transpose(), error

In [4]:
# Definición del sistema lineal a resolver y el vector inicial v_0

Ax_b = np.array([[10, -1, 2, 0, 6],
                 [-1, 11, -1, 3, 25],
                 [2, -1, 10, -1, -11],
                 [0, 3, -1, 8, 15]])
v_0 = np.array([0, 0, 0, 0])
print(f'El sistema Ax = b:\n{Ax_b[:, :-1]} = \n{Ax_b[:, -1].reshape((4, 1))}\n\nEl vector inicial es:\n{v_0}')

El sitema Ax = b:
[[10 -1  2  0]
 [-1 11 -1  3]
 [ 2 -1 10 -1]
 [ 0  3 -1  8]] = 
[[  6]
 [ 25]
 [-11]
 [ 15]]

El vector inicial es:
[0 0 0 0]


In [5]:
# Sacamos su transformación Tx = c
T, c = transformar_sistema(Ax_b[:, :-1], Ax_b[:, -1])
c

array([ 0.6       ,  2.27272727, -1.1       ,  1.875     ])

In [6]:
table_vk, error = met_jacobi(T, c, v_0, tol=10 ** (-3), n_iteration=10, norm=1)
table_vk

array([[ 0.    ,  0.6   ,  1.0473,  0.9326,  1.0152,  0.989 ,  1.0032,
         0.9981,  1.0006,  0.9997],
       [ 0.    ,  2.2727,  1.7159,  2.0533,  1.9537,  2.0114,  1.9922,
         2.0023,  1.9987,  2.0004],
       [ 0.    , -1.1   , -0.8052, -1.0494, -0.9681, -1.0103, -0.9945,
        -1.002 , -0.999 , -1.0004],
       [ 0.    ,  1.875 ,  0.8852,  1.1309,  0.9738,  1.0214,  0.9944,
         1.0036,  0.9989,  1.0006]])

In [7]:
table_vk, error = met_jacobi(T, c, v_0, tol=10 ** (-3), n_iteration=11, norm=2)
table_vk

array([[ 0.    ,  0.6   ,  1.0473,  0.9326,  1.0152,  0.989 ,  1.0032,
         0.9981,  1.0006,  0.9997,  1.0001],
       [ 0.    ,  2.2727,  1.7159,  2.0533,  1.9537,  2.0114,  1.9922,
         2.0023,  1.9987,  2.0004,  1.9998],
       [ 0.    , -1.1   , -0.8052, -1.0494, -0.9681, -1.0103, -0.9945,
        -1.002 , -0.999 , -1.0004, -0.9998],
       [ 0.    ,  1.875 ,  0.8852,  1.1309,  0.9738,  1.0214,  0.9944,
         1.0036,  0.9989,  1.0006,  0.9998]])

In [8]:
# Tomemos el vector inicial 
v_0 = np.array([1, 2, 1, 2])
table_vk, error = met_jacobi(T, c, v_0, tol=10 ** (-3), n_iteration=11, norm=1)
table_vk

array([[ 1.    ,  0.6   ,  0.9709,  0.9713,  0.9992,  0.9965,  1.0002,
         0.9995,  1.0001],
       [ 2.    ,  1.9091,  1.9045,  1.9934,  1.9844,  2.0001,  1.9976,
         2.0002,  1.9996],
       [ 1.    , -0.9   , -0.9041, -0.9991, -0.9901, -1.0011, -0.9986,
        -1.0003, -0.9998],
       [ 2.    ,  1.25  ,  1.0466,  1.0478,  1.0026,  1.0071,  0.9998,
         1.0011,  0.9999]])